"""Server-rendered management UI.

Every mutation calls the same service objects as the JSON API and returns the
affected list partial plus an out-of-band flash message, so htmx can swap both
in one response.
"""

from __future__ import annotations

import json
import uuid
from pathlib import Path
from typing import Annotated

from fastapi import APIRouter, Depends, Form, Request
from fastapi.responses import HTMLResponse

from app.dependencies import (
    get_container,
    get_domain_service,
    get_example_service,
    get_index_manager,
    get_intent_service,
)
from app.errors import InvalidInputError
from app.models.classification import ClassifyRequest
from app.models.domain import DomainCreate, DomainUpdate
from app.models.example import ExampleCreate
from app.models.intent import IntentCreate, ToolRef
from app.observability import tracing
from app.services.container import Container
from app.services.domain_service import DomainService
from app.services.evaluation import run_evaluation
from app.services.example_service import ExampleService
from app.services.index_manager import IndexManager
from app.services.intent_service import IntentService
from app.services.strategies import BUILTIN_STRATEGIES
from app.ui.templating import templates

router = APIRouter(tags=["ui"], include_in_schema=False)

#: Generated by scripts/build_api_docs.py; served at /ui/api.
API_DOCS_PATH = Path(__file__).resolve().parents[2] / "api-documentation.html"


def _flash(message: str, level: str = "success") -> str:
    return f'<div id="flash" class="flash {level}" hx-swap-oob="true">{message}</div>'


def _partial(request: Request, name: str, context: dict, flash: str | None = None) -> HTMLResponse:
    response = templates.TemplateResponse(request=request, name=name, context=context)
    if flash:
        body = response.body.decode() + flash
        return HTMLResponse(body)
    return response


# --------------------------------------------------------------------- pages
@router.get("/", response_class=HTMLResponse)
def dashboard(request: Request, domains: DomainService = Depends(get_domain_service)):
    return templates.TemplateResponse(
        request=request, name="pages/dashboard.html", context={"domains": domains.list()}
    )


@router.get("/ui/domains/{domain_id}", response_class=HTMLResponse)
def domain_page(
    request: Request,
    domain_id: str,
    domains: DomainService = Depends(get_domain_service),
    intents: IntentService = Depends(get_intent_service),
    indexes: IndexManager = Depends(get_index_manager),
):
    domain = domains.read(domain_id)
    return templates.TemplateResponse(
        request=request,
        name="pages/domain.html",
        context={
            "domain": domain,
            "intents": intents.list(domain_id),
            "status": indexes.status(domain_id),
        },
    )


@router.get("/ui/domains/{domain_id}/intents/{intent_id}", response_class=HTMLResponse)
def intent_page(
    request: Request,
    domain_id: str,
    intent_id: str,
    domains: DomainService = Depends(get_domain_service),
    intents: IntentService = Depends(get_intent_service),
    examples: ExampleService = Depends(get_example_service),
    indexes: IndexManager = Depends(get_index_manager),
):
    return templates.TemplateResponse(
        request=request,
        name="pages/intent.html",
        context={
            "domain": domains.get(domain_id),
            "intent": intents.read(domain_id, intent_id),
            "examples": examples.list(domain_id, intent_id),
            "status": indexes.status(domain_id),
        },
    )


@router.get("/ui/playground", response_class=HTMLResponse)
def playground(
    request: Request,
    domain: str | None = None,
    domains: DomainService = Depends(get_domain_service),
    container: Container = Depends(get_container),
):
    return templates.TemplateResponse(
        request=request,
        name="pages/playground.html",
        context={
            "domains": domains.list(),
            "selected": domain,
            "strategies": list(BUILTIN_STRATEGIES.values()),
            "extraction_available": container.entity_extractor.available,
            "extraction_enabled": container.entity_extractor.enabled,
            "provider": container.entity_extractor.provider_name,
            "sessions_enabled": container.sessions.enabled,
            "suggested_session": f"play-{uuid.uuid4().hex[:8]}",
        },
    )


@router.get("/ui/operations", response_class=HTMLResponse)
def operations(
    request: Request,
    container: Container = Depends(get_container),
    domains: DomainService = Depends(get_domain_service),
):
    """Index health, configuration and recent audit activity in one place."""
    statuses = []
    for domain in domains.list():
        status = container.index_manager.status(domain.id)
        statuses.append(
            {
                "domain": domain,
                "status": status,
                "in_sync": status.bm25_doc_count == status.dense_count,
            }
        )
    return templates.TemplateResponse(
        request=request,
        name="pages/operations.html",
        context={
            "statuses": statuses,
            "settings": container.settings,
            "auth_enabled": container.authenticator.enabled,
            "key_count": container.authenticator.key_count,
            "extraction_available": container.entity_extractor.available,
            "extraction_enabled": container.entity_extractor.enabled,
            "provider": container.entity_extractor.provider_name,
            "tracing_enabled": tracing.enabled(),
            "ab_enabled": container.strategies.enabled,
            "variants": container.strategies.variants,
            "audit_entries": container.audit.tail(25),
            "audit_enabled": container.audit.enabled,
        },
    )


@router.get("/ui/api", response_class=HTMLResponse)
def api_reference(request: Request):
    """The generated API reference, served as part of the UI.

    It is produced from the live OpenAPI schema by scripts/build_api_docs.py, so
    it cannot drift from the code. If it has not been generated, point at the
    interactive docs rather than showing a broken page.
    """
    if API_DOCS_PATH.exists():
        return HTMLResponse(API_DOCS_PATH.read_text("utf-8"))
    return templates.TemplateResponse(
        request=request,
        name="pages/error.html",
        context={
            "status_code": 404,
            "message": (
                "api-documentation.html has not been generated yet. Run "
                "'uv run python -m scripts.build_api_docs', or use /docs for the "
                "interactive Swagger UI."
            ),
        },
        status_code=404,
    )


@router.get("/ui/evaluation", response_class=HTMLResponse)
def evaluation_page(request: Request):
    return templates.TemplateResponse(request=request, name="pages/evaluation.html", context={})


@router.post("/ui/evaluation/run", response_class=HTMLResponse)
async def ui_run_evaluation(
    request: Request,
    variant: Annotated[str, Form()] = "",
    container: Container = Depends(get_container),
):
    """Run the held-out evaluation set against the live catalogue."""
    report = await run_evaluation(container, variant or None)
    return templates.TemplateResponse(
        request=request,
        name="partials/evaluation_result.html",
        context={"report": report, "settings": container.settings},
    )


# ----------------------------------------------------------------- mutations
@router.post("/ui/domains", response_class=HTMLResponse)
def ui_create_domain(
    request: Request,
    name: Annotated[str, Form()],
    description: Annotated[str, Form()] = "",
    system_instructions: Annotated[str, Form()] = "",
    user_instructions: Annotated[str, Form()] = "",
    domains: DomainService = Depends(get_domain_service),
):
    domains.create(
        DomainCreate(
            name=name,
            description=description,
            system_instructions=system_instructions,
            user_instructions=user_instructions,
        )
    )
    return _partial(
        request,
        "partials/domain_list.html",
        {"domains": domains.list()},
        _flash(f"Domain '{name}' created."),
    )


@router.post("/ui/domains/{domain_id}/instructions", response_class=HTMLResponse)
def ui_update_instructions(
    request: Request,
    domain_id: str,
    system_instructions: Annotated[str, Form()] = "",
    user_instructions: Annotated[str, Form()] = "",
    domains: DomainService = Depends(get_domain_service),
):
    domains.update(
        domain_id,
        DomainUpdate(system_instructions=system_instructions, user_instructions=user_instructions),
    )
    return HTMLResponse(_flash("Extraction instructions saved."))


@router.delete("/ui/domains/{domain_id}", response_class=HTMLResponse)
def ui_delete_domain(
    request: Request, domain_id: str, domains: DomainService = Depends(get_domain_service)
):
    domain = domains.get(domain_id)
    domains.delete(domain_id)
    return _partial(
        request,
        "partials/domain_list.html",
        {"domains": domains.list()},
        _flash(f"Domain '{domain.name}' deleted."),
    )


@router.post("/ui/domains/{domain_id}/intents", response_class=HTMLResponse)
def ui_create_intent(
    request: Request,
    domain_id: str,
    name: Annotated[str, Form()],
    description: Annotated[str, Form()] = "",
    tool_name: Annotated[str, Form()] = "",
    tool_version: Annotated[str, Form()] = "v1",
    entity_schema: Annotated[str, Form()] = "",
    extraction_hints: Annotated[str, Form()] = "",
    domains: DomainService = Depends(get_domain_service),
    intents: IntentService = Depends(get_intent_service),
):
    domains.get(domain_id)
    intents.create(
        domain_id,
        IntentCreate(
            name=name,
            description=description,
            tool=ToolRef(name=tool_name, version=tool_version or "v1"),
            entity_schema=_parse_schema(entity_schema),
            extraction_hints=extraction_hints,
        ),
    )
    return _partial(
        request,
        "partials/intent_list.html",
        {"domain": domains.read(domain_id), "intents": intents.list(domain_id)},
        _flash(f"Intent '{name}' created."),
    )


@router.delete("/ui/domains/{domain_id}/intents/{intent_id}", response_class=HTMLResponse)
def ui_delete_intent(
    request: Request,
    domain_id: str,
    intent_id: str,
    domains: DomainService = Depends(get_domain_service),
    intents: IntentService = Depends(get_intent_service),
):
    intent = intents.get(domain_id, intent_id)
    intents.delete(domain_id, intent_id)
    return _partial(
        request,
        "partials/intent_list.html",
        {"domain": domains.read(domain_id), "intents": intents.list(domain_id)},
        _flash(f"Intent '{intent.name}' deleted."),
    )


@router.post("/ui/domains/{domain_id}/intents/{intent_id}/examples", response_class=HTMLResponse)
def ui_add_example(
    request: Request,
    domain_id: str,
    intent_id: str,
    text: Annotated[str, Form()],
    domains: DomainService = Depends(get_domain_service),
    examples: ExampleService = Depends(get_example_service),
):
    domains.get(domain_id)
    examples.add(domain_id, intent_id, ExampleCreate(text=text))
    return _partial(
        request,
        "partials/example_list.html",
        {
            "domain_id": domain_id,
            "intent_id": intent_id,
            "examples": examples.list(domain_id, intent_id),
        },
        _flash("Example added and index rebuilt."),
    )


@router.delete(
    "/ui/domains/{domain_id}/intents/{intent_id}/examples/{example_id}",
    response_class=HTMLResponse,
)
def ui_delete_example(
    request: Request,
    domain_id: str,
    intent_id: str,
    example_id: str,
    examples: ExampleService = Depends(get_example_service),
):
    examples.delete(domain_id, intent_id, example_id)
    return _partial(
        request,
        "partials/example_list.html",
        {
            "domain_id": domain_id,
            "intent_id": intent_id,
            "examples": examples.list(domain_id, intent_id),
        },
        _flash("Example deleted and index rebuilt."),
    )


@router.post("/ui/domains/{domain_id}/reindex", response_class=HTMLResponse)
def ui_reindex(
    request: Request,
    domain_id: str,
    domains: DomainService = Depends(get_domain_service),
    indexes: IndexManager = Depends(get_index_manager),
):
    domains.get(domain_id)
    indexes.rebuild(domain_id)
    return _partial(
        request,
        "partials/index_status.html",
        {"status": indexes.status(domain_id)},
        _flash("Index rebuilt."),
    )


@router.post("/ui/playground/classify", response_class=HTMLResponse)
async def ui_classify(
    request: Request,
    domain: Annotated[str, Form()],
    text: Annotated[str, Form()],
    extract_entities: Annotated[str, Form()] = "",
    variant: Annotated[str, Form()] = "",
    session_id: Annotated[str, Form()] = "",
    container: Container = Depends(get_container),
):
    payload = ClassifyRequest(
        domain=domain,
        text=text,
        extract_entities=True if extract_entities else None,
        variant=variant or None,
        session_id=session_id.strip() or None,
    )
    result = await container.classification.classify(payload, debug=True)
    turns = container.sessions.all_turns(payload.session_id) if payload.session_id else []
    return templates.TemplateResponse(
        request=request,
        name="partials/classify_result.html",
        context={"result": result, "settings": container.settings, "turns": turns},
    )


@router.delete("/ui/playground/session/{session_id}", response_class=HTMLResponse)
def ui_clear_session(
    request: Request, session_id: str, container: Container = Depends(get_container)
):
    removed = container.sessions.clear(session_id)
    return HTMLResponse(_flash(f"Session cleared ({removed} turn(s) forgotten)."))


def _parse_schema(raw: str) -> dict:
    raw = (raw or "").strip()
    if not raw:
        return {}
    try:
        parsed = json.loads(raw)
    except json.JSONDecodeError as exc:
        raise InvalidInputError(f"entity schema is not valid JSON: {exc.msg}") from exc
    if not isinstance(parsed, dict):
        raise InvalidInputError("entity schema must be a JSON object")
    return parsed
