"""Repository protocols.

Services depend only on these, so the Chroma-backed implementations can be
swapped for a relational backend later without touching the engine.
"""

from __future__ import annotations

from typing import Protocol

from app.models.classification import DenseHit
from app.models.domain import DomainConfig
from app.models.example import Example
from app.models.intent import IntentConfig


class DomainRepository(Protocol):
    def get(self, domain_id: str) -> DomainConfig | None: ...
    def get_by_name(self, name: str) -> DomainConfig | None: ...
    def list(self) -> list[DomainConfig]: ...
    def save(self, domain: DomainConfig) -> DomainConfig: ...
    def delete(self, domain_id: str) -> None: ...


class IntentRepository(Protocol):
    def get(self, intent_id: str) -> IntentConfig | None: ...
    def get_by_name(self, domain_id: str, name: str) -> IntentConfig | None: ...
    def list_for_domain(self, domain_id: str) -> list[IntentConfig]: ...
    def list_all(self) -> list[IntentConfig]: ...
    def save(self, intent: IntentConfig) -> IntentConfig: ...
    def delete(self, intent_id: str) -> None: ...
    def delete_for_domain(self, domain_id: str) -> None: ...


class ExampleRepository(Protocol):
    def get(self, example_id: str) -> Example | None: ...
    def list_for_intent(self, intent_id: str) -> list[Example]: ...
    def list_for_domain(
        self, domain_id: str, intent_ids: list[str] | None = None
    ) -> list[Example]: ...
    def find_by_hash(self, intent_id: str, text_hash: str) -> Example | None: ...
    def add_many(self, examples: list[Example], embeddings: list[list[float]]) -> None: ...
    def delete(self, example_id: str) -> None: ...
    def delete_for_intent(self, intent_id: str) -> None: ...
    def delete_for_domain(self, domain_id: str) -> None: ...
    def count_by_intent(self, domain_id: str | None = None) -> dict[str, int]: ...
    def count_for_domain(self, domain_id: str) -> int: ...
    def rename_intent(self, intent_id: str, intent_name: str) -> None: ...
    def query_dense(
        self, domain_id: str, vector: list[float], top_k: int, intent_ids: list[str]
    ) -> list[DenseHit]: ...
